### ISSUE TITLE
Cannot find module 'puppeteer' from 'puppet-scraper.cjs.development.js'

### ISSUE THREAD

**Issue by moltar** [grikomsn/puppet-scraper#11]
Getting the following errors in Jest when trying to use the module:

```
    Cannot find module 'puppeteer' from 'puppet-scraper.cjs.development.js'

    Require stack:
      node_modules/puppet-scraper/dist/puppet-scraper.cjs.development.js
      node_modules/puppet-scraper/dist/index.js
      src/puppeteer.ts
      src/puppeteer.test.ts

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:299:11)
      at Object.<anonymous> (node_modules/puppet-scraper/dist/puppet-scraper.cjs.development.js:8:33)
```

I think it is probably this line:

https://github.com/grikomsn/puppet-scraper/blob/356e339460497a3ed6b927ac74ebd05fd8a20744/src/puppet-scraper.ts#L2

It assumes one has `puppeteer` installed, but in reality it is also possible to use only `puppeteer-core`.

I think, in fact, it would be the preferred way for a library to use the `-core` version, as it wouldn't pull in Chromium by default.

**Comment by moltar** [comment]
Just looked inside the `package.json`, and there seems to be a mis-match.

The dependency is declared as `puppeteer-core`, but peer dep is `puppeteer` and the actual code uses `puppeteer`.

**Comment by grikomsn** [comment]
Thanks for the heads up! Will do a fix after this, or if you want to submit a PR that's also great. 😄
